# This contains params to be used by the stages to train or predict
# This contains params to be used by the stages to train or predict
prepare:
  split: 0.3
  seed: 2022
  tag: <python>

featurize:
  max_features: 5000
  n_grams: 2

train:
  seed: 4000
  n_est: 500
  min_split: 16
  n_jobs: -1
